### ISSUE TITLE
Same file issue

### ISSUE THREAD

**Issue by Znow** [PerfectlyNormal/tinymce-rails-imageupload#84]
Hi

The gem version 4, got updated, and when I try to deploy, this is happening:

```
rake aborted!
ArgumentError: same file: /home/app/releases/20170306133950/public/assets/tinymce/plugins/uploadimage/langs/da-7863a445de5898068b220fca3eca142f387ea9036f830c1a93416781d0f169a3.js and /home/findveji-production/releases/20170306133950/public/assets/tinymce/plugins/uploadimage/langs/da.js
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_installer/copy.rb:42:in `block in move_asset'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_installer.rb:58:in `with_asset'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_installer/copy.rb:5:in `with_asset'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_installer/copy.rb:40:in `move_asset'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_installer/copy.rb:23:in `block (2 levels) in cleanup_assets'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_manifest.rb:111:in `block in remove_digest'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_manifest.rb:23:in `asset_path'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_manifest.rb:107:in `remove_digest'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_installer/copy.rb:22:in `block in cleanup_assets'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_manifest.rb:16:in `block in each'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_manifest.rb:14:in `each_key'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_manifest.rb:14:in `each'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_installer/copy.rb:21:in `cleanup_assets'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_installer/copy.rb:12:in `call'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-4.5.4/lib/tinymce/rails/asset_installer.rb:22:in `install'
/home/app/shared/bundle/ruby/2.3.0/gems/tinymce-rails-imageupload-4.0.17.beta/lib/tasks/tinymce-uploadimage-assets.rake:13:in `block in <top (required)>'
/home/app/shared/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

**Comment by botimer** [comment]
I think this will be resolved by pull requests #77 and #88.

**Comment by PerfectlyNormal** [comment]
Try with v4.0.17.beta.3

**Comment by johncox00** [comment]
I'm having this issue even with the latest version. :(
